### PR TITLE
add -cors flag

### PR DESCRIPTION
**Pull request by nickdesaulniers**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
as a heads up, I was able to use https://github.com/indexzero/http-server with Dashcast and everything worked!

**Comment by cconcolato** [comment]
Thank you for this PR. We will try to do some further cleaning as the sending of init segment in chunked mode is not needed and adds some useless complexity (e.g. your problem of the missing call to res.end() in that case).

**Comment by cconcolato** [comment]
Thanks also for the information about https://github.com/indexzero/http-server working with DashCast. Were you able to do low latency with it as well? Are you suggesting we should replace gpac/node-gpac-dash with indexzero/http-server?

**Comment by nickdesaulniers** [comment]
> Are you suggesting we should replace gpac/node-gpac-dash with indexzero/http-server?

I recognize a lot of hard work went into this server.  I don't fully understand the implications of all of the logic involved (when to chunk), but I do know that the benefit of DASH over RTSP is a simpler protocol (HTTP) at the expense of more client side application logic.  This should allow for the usage of a simpler server (a simple file server, even) at least for on demand content.

http-server worked for me with gpac's DashCast and google's ShakaPlayer when streaming my desktop.  I've been having some issues with capturing from the camera (OSX) (not sure if it's the client, the server, or the hardware; but I'll file bugs).

**Comment by cconcolato** [comment]
You're right DASH allows using a very simple HTTP server. The code in this project was developed as part of research/PhD work to achieve low latency live DASH and in that case you need coordination between the content generator and the server and the server needs chunk encoding. 

The concepts behind this software are described in this research paper if you're interested: http://biblio.telecom-paristech.fr/cgi-bin/download.cgi?id=14719 

We've also been able to demonstrate bidirectional communication and hybrid broadcast broadband using this server. More details here: http://biblio.telecom-paristech.fr/cgi-bin/download.cgi?id=15580

**Comment by nickdesaulniers** [comment]
Wow, very cool, thanks for sharing!

**Pull request merged**
